### ISSUE TITLE
crash while trying to navigate into an empty view (?)

### ISSUE THREAD

**Issue by yusdacra** [bluskript/nix-inspect#1]
While trying to move into a (still loading?) empty view a panic happens:

```
thread 'main' panicked at src/model.rs:239:27:
index out of bounds: the len is 0 but the index is 0
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

<a href="https://asciinema.org/a/t2ShJbwxjo91X9WmToz3YX00V" target="_blank"><img src="https://asciinema.org/a/t2ShJbwxjo91X9WmToz3YX00V.svg" /></a>

**Comment by bluskript** [comment]
Fixed in aad35e2e990c0e7bb8b75c72ebd163af52236a97
