### ISSUE TITLE
Weird glitch when not providing a path

### ISSUE THREAD

**Issue by Nebucatnetzer** [bluskript/nix-inspect#15]
When I don't provide a path I'm getting weird glitches and my terminal breaks.
When I add `--path .` it works fine.
It's with the latest version from this repo.

![image](https://github.com/bluskript/nix-inspect/assets/2287221/af1e6558-fd6c-4d26-9d3e-d77613fb120a)

**Comment by bluskript** [comment]
I made it so that if a path isn't provided, and /etc/nixos doesn't exist, then it'll load from cwd. Thanks for the input!

**Comment by Nebucatnetzer** [comment]
I saw that it output something about /etc/nixos but that path actually exists on my system.
It contains a flake.nix symlink to the config in my home directory.

**Comment by Spiker985** [comment]
Just to add to this (though I'm necroing the issue), this just happened to me on version 0.1.2 because I _also_ have a symlinked file in /etc/nixos

So perhaps look into proper handling of symlinks, or at least add a check, so you can abort running and give instructions to users?
