### ISSUE TITLE
Doesn't build on x86_64-linux

### ISSUE THREAD

**Issue by nadir-ishiguro** [bluskript/nix-inspect#7]
Hi, 
Just found about this tool and wanted to give it a try. Running `nix run github:bluskript/nix-inspect` gave me:

```
trying https://crates.io/api/v1/crates/indoc/2.0.4/download
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (35) Recv failure: Connection reset by peer
error: cannot download download-indoc-2.0.4 from any mirror
```

My machine: 
```
nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.8.5-cachyos, NixOS, 24.05 (Uakari), 24.05.20240408.4cba8b5`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.2`
 - nixpkgs: `/etc/nix/path/nixpkgs`
```

**Comment by bluskript** [comment]
Appears to be a network issue, "Connection reset by peer" suggests crates.io might be refusing connections from your ip. Are you on a VPN by chance?

**Comment by bluskript** [comment]
Likely not an issue with the project, closing unless more people can reproduce

**Comment by ri0t** [comment]
I have the same problem here, i'm not on a VPN and otherwise have no network troubles. But yes, this makes it look very much like it's a crates.io issue. Will try again, later.

Some nixpkg-foam would be very appreciated 😉

**Comment by nadir-ishiguro** [comment]
Definitely a crates.io issue. I've repeated installs and it failed with a different crate each time until it finally worked in the end.
